config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  resources:contacts
  get '/about' => 'pages#about'
  get '/stuff' => 'pages#stuff'
  root'pages#home'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
    validates :name, presence:true
    validates :email, presence:true
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/plan.rb
class Plan < ActiveRecord::Base
has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         belongs_to :plan
         has_one :profile
         attr_accessor:stripe_card_token
           
           def save_with_payment
               if valid?
                 customer= Stripe::Customer.create(description:email, plan:plan_id, card:stripe_card_token)
                 self.stripe_customer_token= customer.id
                 save!
               end
           end
end
 

app/controllers/Users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def create
         super do |resource|
           
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :stripe_card_token, :email, :password, :password_confirmation) }
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
    def new
         @contact = Contact.new
    end
    
  def create
      @contact=Contact.new(contact_params)
    if @contact.save
        name =  params[:contact]  [:name]
        email =  params[:contact] [:email]
        body = params[:contact]  [:comments]
        ContactMailer.contact_email(name, email, body).deliver
        flash[:success] = 'Message sent.'
        redirect_to login_path
    else
        flash[:danger]="Error, message not sent. Is your Email address ok?"
         redirect_to new_contact_path
    end
    
  end

    private
        def contact_params
            params.require(:contact).permit(:name,:email,:comments)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end

    def about
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    # form where a user can fill out their own profile.
    @user = User.find( params[:user_id] )
    @profile = Profile.new
  end
  def create 
    @user = User.find( params[:user_id] )
    @profile = @user.build_profile(profile_params)
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :new
    end
  end
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :job_title, :phone_number, :contact_email, :description)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
    def create
         super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_payment
        else
          resource.save
        end
      end
    end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find( params[:id] )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<div class="row">
    
  <div class="col-md-4 col-md-offset-4">
    <div class="well">
      <%= form_for @contact do |f| %>
      
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :email %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :comments %>
          <%= f.text_area :comments, class: 'form-control' %>
        </div>
        
        <%= f.submit 'Submit', class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reg Gordon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
  <%= javascript_include_tag 'application' %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
     <div class='container'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to root_path, class: 'navbar-brand' do %>
          <i class="fa fa-users"></i>
        Home Jeeves
      <% end %>
    </div>
    
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <div class="nav navbar-nav navbar-right">
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-primary navbar-btn' %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, class: 'btn btn-primary navbar-btn', method: :get %>

        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "about", about_path %></li>
            <li><%= link_to "stuff", stuff_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
            <li><%= link_to "Create your profile!", new_user_profile_path(current_user) if current_user %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
<div class='container'>
  
  <% flash.each do |key, value| %>
  <%= content_tag :div, value, class:" alert alert-#{key}" %>
  <%end%>
  
<%= yield %>

</div>

</body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron">

<h2>about us</h2>
</div>

app/views/pages/home.html.erb
<div class="jumbotron text-center">
  <h1>Welcome to Dev Match</h1>
  <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>
<div class="row">
  
  <% if user_signed_in? %>
    <div class="col-md-6">
      <div class="well text-center">
        <h2 >Your Profile</h2>
        <% if current_user.profile %>
          <%= link_to "Edit your profile", "#", class: 'btn btn-default btn-lg btn-block' %>
          <%= link_to "View your profile", user_path(current_user), class: 'btn btn-default btn-lg btn-block' %>
        <% else %>
        
          <p>Create your profile so that you can share your information with the community.</p>
          <%= link_to "Create your profile", new_user_profile_path(current_user), class: 'btn btn-default btn-lg btn-block'%>
        <% end %>
      </div>
      
    </div>
    <div class="col-md-6">
      <div class="well text-center">
        <h2 >The Community</h2>
        <p>Visit the community to meet other developers, entrepreneurs, and investors!</p>
        <%= link_to "Visit the community", "#", class: 'btn btn-default btn-lg btn-block' %>
      </div>
    </div>
  <% else %>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Basic Membership</h2>
        <h4>Sign up for free and get basic access to the community.</h4>
        <br/>
        <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="well">
        <h2 class="text-center">Pro Membership</h2>
        <h4>Sign up for the pro account for $10/month and get access to the community and contact information!</h4>
        <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
      </div>
    </div>
  <% end %>
</div>

app/views/pages/login.html.erb
<div class="jumbotron text-center">
    We got your message. Consider yourself:
    
  <h1>Logged in Motherfucker</h1>
  
</div>

app/views/pages/stuff.html.erb
<h2>stuff</h2>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h1 class="text-center">Create Your Profile</h1>
    <p class="text-center">Be a part of the Dev Match community and fill out your profile!</p>
    
    <div class="well">
      <%= form_for @profile, url: user_profile_path do |f| %>
      
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :job_title %>
          <%= f.select :job_title, ['Stripper', 'Murderer', 'Psycho'], {}, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :phone_number %>
          <%= f.text_field :phone_number, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :contact_email %>
          <%= f.text_field :contact_email, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_area :description, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.submit "Update Profile", class: 'btn btn-primary' %>
        </div>
        
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= @user %><br>
<%=@user.profile.first_name %>
<%= @user.profile.last_name%>

<% if current_user.plan_id==2 %>
<%= @user.profile.contact_email%>
<%= @user.profile.job_title %>
<%end%>